cc_library(
    name = "Millipede",
    srcs = [
        "Millipede.cc", 
        "geometry/Vector.cc", 
        "geometry/Ray.cc",  
        "geometry/Shape.cc",
        "geometry/ShapeList.cc",
        "geometry/Sphere.cc",
        "colour/Colour.cc",  
        "output/Output.cc",
    ],
    hdrs = [
        "Millipede.h", 
        "geometry/Vector.h", 
        "geometry/Ray.h", 
        "geometry/Shape.h",
        "geometry/ShapeList.h",
        "geometry/Sphere.h",
        "colour/Colour.h", 
        "output/Output.h",
    ],
    visibility = ["//main:__pkg__"],
)
