cc_library(
    name = "Millipede",
    srcs = [
        "Millipede.cc", 
        "Vector.cc", 
        "Ray.cc",  
        "Colour.cc",  
        "Output.cc"
    ],
    hdrs = [
        "Millipede.h", 
        "Vector.h", 
        "Ray.h", 
        "Colour.h", 
        "Output.h"
    ],
    visibility = ["//main:__pkg__"],
)
